[book]
authors = ["Denys Vuika"]
language = "en"
multilingual = false
src = "src"
title = "Angular Book"

[output.html]
git-repository-url = "https://github.com/DenysVuika/angular-book"
cname = "angular-book.dev"
google-analytics = "G-23X2CQXZ48"
